import { getWeb3StorageUrl } from "@/lib/ipfs";

export const videoPlaceHolder = getWeb3StorageUrl("bafkreidhz6j4jdl6sgbg7s5jeu36eyvvwaih4pjzun4o2xbphbir63bf34");

export const videoPrompt = (assessment: string):string =>{
    
    return "Ignore the attached image if any. Focus on the assessment of a specialised AI deepfake detection model, which is included here, (in one line csv format) .\"\"\"" 
    + assessment + 
    "\"\"\" The closer the number is to 1, the more likely the video is a deepfake. The close the number is to 0, the more likely the video is real. "+
    "Please provide a brief summary of the results and limit your aswer only to this matter."
}

export const imagePrompt = (assessment: string):string =>{
    
    return "The assessment of a specialised AI deepfake detection model on a picture is included here \"\"\""+assessment+"\"\"\""+
    " If the assessment, and the response is not clear, please look at the attached picture and provide your own assessment:\n"+
    assistantPrompt;
}

const assistantPrompt = "You are an expert in analysing images and understanding whether they have been generated or modified by Artifial intellignece methods and tools."+
"The probability of being AI-generated should be provided on a scale of 0 to 1."+
"The higher the value, the higher the probability that the image was generated by AI."+
"You should express your confidence in the analysis by providing this probability."+
"By default, provide a summary of the analysis and the probability of being AI-generated.";

/*
"Your response should be in JSON format."+

"The json format should contain the following fields:"+
- hash: the images sha256 hash.
- summary: A summary of your analysis with the reasons behind it.
- result: The probability of the image being AI-generated on a scale of 0 to 1.

In case something goes wrong and you cannot process the provided file, return a reuslt of -1, and add an error description in the summary field.

In case anything else apart from an image and maybe a short decsription is asked of you, any unrelated subject , please refuse to respond in a kind manner.}';
*/