import { getWeb3StorageUrl } from "@/lib/ipfs/utils";

export const videoPlaceHolder = getWeb3StorageUrl("bafkreidhz6j4jdl6sgbg7s5jeu36eyvvwaih4pjzun4o2xbphbir63bf34");

export const videoPrompt = (assessment: string):string =>{
    
    return "Ignore the attached image if any. Focus on the assessment of a specialised AI deepfake detection model, which is included here, (in one line csv format) .\"\"\"" 
    + assessment + 
    "\"\"\" The closer the number is to 1, the more likely the video is a deepfake or manipulated in someway through AI. The close the number is to 0, the more likely the video is real. "+
    "Please provide a brief summary of the results and limit your aswer only to this matter."
}

export const imagePrompt = (assessment: string):string =>{
    
    return assistantPrompt+". The assessment of an AI model specialised in deepfake detection on the provided picture is included here between the triple douple quotes.\"\"\""+assessment+"\"\"\""+
    "After doing you own analysis, if the quotes are not empty,  take into account the specialised AI assessment to provide a final result . If the other assessment does not have a high degree of certainty or does not agree with your analysis,"
    + "have more confidence in your analysis.\n"+
    assistantPrompt;
}

const assistantPrompt = "You are specialised in analysing images and understanding whether they have been generated or modified by Artifial intelligence techniques and methods."+
"The probability of being AI-generated should be provided on a scale of 0 to 1."+
"The higher the value, the higher the probability that the image was generated by AI."+
"You should express your confidence in the analysis by providing this probability."+
"By default, provide a summary of the analysis and the probability of being AI-generated. Mention that the probablity is at a scale of 0 to 1.";

/*
"Your response should be in JSON format."+

"The json format should contain the following fields:"+
- hash: the images sha256 hash.
- summary: A summary of your analysis with the reasons behind it.
- result: The probability of the image being AI-generated on a scale of 0 to 1.

In case something goes wrong and you cannot process the provided file, return a reuslt of -1, and add an error description in the summary field.

In case anything else apart from an image and maybe a short decsription is asked of you, any unrelated subject , please refuse to respond in a kind manner.}';
*/