import type { Metadata } from "next";
import { Inter as FontSans} from "next/font/google";
import "./globals.css";
import { cookieToInitialState } from 'wagmi';
import Header from "./head";
import { headers } from "next/headers";
import Web3ModalProvider from "@/components/wallet/Web3ModalProvider";
import { customConfig } from "@/components/wallet/wagmiConfig";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { cn } from "@/lib/utils"
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(customConfig, headers().get('cookie'))
  return (
    <html lang="en">
      <body  className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
