[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
galadriel = "https://devnet.galadriel.com"
lilypad = "http://testnet.lilypad.tech:8545"
coophive = "http://halcyon.co-ophive.network:8545"